config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'

  match '/signup', to: 'users#new', via: 'get'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" id="header">
    <div class="container">
        <%= link_to "HUANTARGET", root_path, id: "logo" %></h1>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li class="menu_item"><%= link_to "PERSONAL BLOG","#" %></li>
                <li class="menu_item"><%= link_to "PROF BLOG", "#" %></li>
                <li class="menu_item"><%= link_to "PROJECTS", "#" %></li>
                <li class="menu_item"><%= link_to "FOR RECRUITERS", about_path %></li>
                <li class="menu_item"><%= link_to "CONTACT ME", contact_path %></li>
                <li class="menu_item"><%= link_to "SIGN UP",  signup_path %></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HuanTarget | <%= yield(:title) %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container" id="content">
        <%= yield %>
    </div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About me') %>
About me

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contacts') %>
skype: huan-target

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="container-fluid">
    <div id="home_content" class = "jumbotron">
        Hi there!<br>
        My name is Ivan Zverev.<br>
        I'm from Ukraine (Kiev).<br>
        And I think I'm Ruby on Rails developer :)<br>
    </div>
    <%= image_tag("ava.jpg", :alt => "rss feed", :class => "img-rounded", :id => "avatar") %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'SignUp') %>
<h1>SignUp</h1>
<p>Find me in app/views/users/new.html.erb</p>